---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: bourguiga
    password: 9c110fe3-fbdd-4006-a481-d4b1e9e67f6e

- name: Tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: bourguiga/cd_projet
    tag: end
    push: yes
